### Calculate Spherical Coordinates and Geographical Coordinates using Advection Vectors and Height

In [2]:
import wradlib as wrl
import numpy as np

In [36]:
def get_coordinates(x, y, z, site):
    re = wrl.georef.get_earth_radius(site[1])
    
    rad = wrl.georef.proj4_to_osr(('+proj=aeqd +lon_0={lon:f} ' +
                        '+lat_0={lat:f} +ellps=WGS84 +datum=WGS84 ' +
                        '+units=m +no_defs').format(lon=site[0],
                                                    lat=site[1]))
    stack = np.stack((x,y,z), axis=-1)
    if stack.ndim == 1:
        stack = stack[None, :]
        
    r, phi, theta = wrl.georef.xyz_to_spherical(stack, alt=site[2], proj=rad)
    
    spherical = np.stack((r, phi, theta), axis=-1)
    lla = wrl.georef.reproject(stack, projection_source=rad)
    
    
    return spherical, lla

In [39]:
# Radar Bonn
site = (7.071626, 50.730554, 99.5)

In [38]:
# Zur Veranschaulichung, es geht auch mit Feldern
x = np.array([5000, 6000])
y = np.array([5000, 6000])
z = np.array([1000, 2000])
spherical, lla = get_coordinates(x, y, z, site)
print(spherical)
print(lla)

[[7.12863064e+03 4.50000000e+01 7.23321407e+00]
 [8.69653410e+03 4.50000000e+01 1.25943776e+01]]
[[   7.14251187   50.7754789  1000.        ]
 [   7.15670534   50.78445866 2000.        ]]


In [42]:
#Hier als Beispiel mit jeweils einem x,y, und z-Wert, geht aber auch mit obigen Feldern
spherical, lla = get_coordinates(5000, 5000, 1000, site)
#slant range, azimuth and elevation angle
print(spherical)
#Koordinaten, Hohe unverand
print(lla)

[[7128.63064446   45.            7.23321407]]
[[   7.14251187   50.7754789  1000.        ]]
